### ISSUE TITLE
Please answer

### ISSUE THREAD

**Issue by dongpu1813** [FinalHashLLC/eloipool#1]
yiimp   how to install merged-mine-proxy

**Comment by ahmedbodi** [comment]
yiimp doesnt need merged mining proxy

**Comment by dongpu1813** [comment]
How Yiimp established merged mining      auxpow
yiimp what set auxpow

**Comment by ahmedbodi** [comment]
yiimp has build in code for merged mining

**Comment by dongpu1813** [comment]
> yiimp已为合并采矿构建了代码
yiimp what set auxpow
